services:
  - type: web
    name: myfinance-backend
    env: python
    plan: free
    buildCommand: pip install uv && uv pip install -r pyproject.toml --extra backend
    startCommand: uv run uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true 