"""Add category_id to transactions table

Revision ID: 49c69a18767d
Revises: 173ad7416018
Create Date: 2025-08-14 14:46:23.954491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import src.custom_types

# revision identifiers, used by Alembic.
revision = '49c69a18767d'
down_revision = '173ad7416018'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_confirmation_tokens')
    op.add_column('transactions', sa.Column('category_id', src.custom_types.GUID(), nullable=True))
    op.alter_column('transactions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index('idx_transactions_amount', 'transactions', ['amount'], unique=False)
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index('idx_transactions_amount', table_name='transactions')
    op.alter_column('transactions', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('transactions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    
    
    # ### end Alembic commands ### 